# Generated by Django 4.1.5 on 2023-03-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=255)),
                ('Mname', models.CharField(max_length=255)),
                ('Lname', models.CharField(max_length=255)),
                ('MobileNo', models.IntegerField()),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
    ]
